POWERS = {
    'Scratch': 40,
    'Tackle': 40,
    'Pound': 40,
    'Rage': 20,
    'Fury Attack': 15,
    'Ember': 40,
    'Fire Spin': 35,
    'Bubble': 40, 
    'Aqua Jet': 40,
    'Thunder Shock': 40,
    'Thunderbolt': 90,
    'Vine Whip': 45,
    'Magical Leaf': 60,
    'Ice Shard': 40,
    'Double Kick': 30,
    'Earthquake': 100,
    'Wing Attack': 60,
    'Peck': 35,
    'Confusion': 50,
    'Twineedle': 25,
    'Rock Throw': 50,
    'Rock Slide': 75,
    'Lick': 30,
    'Outrage': 120,
    'Crunch': 80,
    'Bite': 60,
    'Flash Cannon': 80,
    'Smog': 30,
    'Dream Eater': 100,
    'Body Slam': 85,
    'Double Slap': 15,
    'Razor Leaf': 55,
    'Headbutt': 70,
    'Absorb': 20, 
    'Fairy Wind': 40, 
    'Struggle Bug': 50, 
    'Draining Kiss': 50,
    'Shadow Ball': 80
}